apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: acrrepo.azurecr.io/nginx:v523341 # Update the repository with the image name and tag
        name: nginx
        resources: {}
      imagePullSecrets:
      - name: nginx-secret  # Update the secret name
status: {}
